apiVersion: batch/v1
kind: Job
metadata:
  name: detect-service
spec:
  template:
    metadata:
      name: detect-service-pod
    spec:
      containers:
      - name: vehicles-detect-service
        image: vehicles-detect-service:latest
        imagePullPolicy: Never
      restartPolicy: Never
